### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by IsitrealSakura** [feightwywx/arcfutil#1]
开始生成songlist
无效的目录：C:\Users\Admin\Desktop\arc.py-master\arc.py-master\songs\anokumene\songconfig.txt
Traceback (most recent call last):
  File "songlist.py", line 484, in <module>
    main()
  File "songlist.py", line 476, in main
    gen_songlist(assetspath)
  File "songlist.py", line 383, in gen_songlist
    songlistsongs.append(songconfig2songlist(songconfig))
  File "songlist.py", line 315, in songconfig2songlist
    difficultylst = eachsong['diff'].split('-')
KeyError: 'diff',                                               idk what is going on rn??? 
![image](https://user-images.githubusercontent.com/68575032/88127400-b4e08980-cbfd-11ea-8e8e-c49d83a5edd3.png)

**Comment by feightwywx** [comment]
Thanks for getting in touch.
However, I found myself forgot to push the latest code. New version added functions about `songconfig.txt`, `packlist` and `bg`, and fixed some bugs. This may help you.

`songconfig.txt` is a plain text file looks like a config file, which is widely used to store Arcaea fanmade song information. For example, a `songconfig.txt` for song "GOODTEK":
```
id=goodtek
title=GOODTEK (Arcaea Edit)
title_en=GOODTEK (Arcaea Edit)
artist=EBIMAYO
bpm=190
bpm_base=190
set=base
purchase=
pv=80842-111157
side=0
bg=
world_unlock=True
date=1487980809
version=1.0
designer_0=Nitro
designer_1=Nitro
designer_2=Nitro
designer_3=GOODTOAST
jacketdesigner_0=Koyama Mai
jacketdesigner_1=Koyama Mai
jacketdesigner_2=Koyama Mai
jacketdesigner_3=出前
jacketOverride_3=True
diff=4-6-9-9+
```
And output info means:
```
Start to generate songlist
Invalid path: C:\Users\Admin\Desktop\arc.py-master\arc.py-master\songs\anokumene\songconfig.txt
```
To be honest, **Idk what you want to do exactly**. If you want to convert files in folder `dl`, I suggest using `sortassets.py`:
```python
python sortassets.py <dlpath>
```

**Comment by IsitrealSakura** [comment]
do you have a discord for me to contact you?

**Comment by feightwywx** [comment]
> do you have a discord for me to contact you?

You could add `.direwolf#8702`.
